### ISSUE TITLE
Just entering a state name will bring up a random district. 

### ISSUE THREAD

**Issue by tobywhughes** [GRMule/gsmap#1]
For example, entering CA for state will return district 22. This bug can be confusing for people who don't know how districts work.

**Comment by GRMule** [comment]
It doesn't end there, haha. I need to look into the google geolocation results more, right now I naively take the first result and run with it. Google, for its part, isn't trying to be precise, it's trying to be helpful. So, it will cough up all kinds of geo coordinates for almost any nonsense you throw at it.

**Comment by GRMule** [comment]
Should do the trick. I only use a result now if it is a street address-level result.
